### ISSUE TITLE
Wyoming Protocol not connecting

### ISSUE THREAD

**Issue by pcwii** [FutureProofHomes/wyoming-enhancements#12]
Your documents do not have any details on installing the wyoming protocol for Home Assistant.
I am unable to do this as it never connects.
Are there details for doing this?
I have tried using the IP address of my Rpi as well as port: 10400, 10700, and 10500.
It looks like the services are loading and that the snapclient is working.

**Comment by markmghali** [comment]
I think he assumes you followed his previous video which walks through the rhasspy steps here

https://github.com/rhasspy/wyoming-satellite/blob/master/docs/tutorial_2mic.md

**Comment by pcwii** [comment]
Yea, my setup works with that tutorial and the required Wyoming device adds fine but after I make the enhancement changes HA no longer sees the device. I will double check my setup.

**Comment by markmghali** [comment]
I had to retrace my steps a few times.

**Comment by FutureProofHomes** [comment]
> I think he assumes you followed his previous video which walks through the rhasspy steps here
> 
> https://github.com/rhasspy/wyoming-satellite/blob/master/docs/tutorial_2mic.md

Correct.  Thanks for the help @markmghali.  

Keep us posted, and if things workout close this tix @pcwii.

**Comment by zac9** [comment]
@pcwii I also just had this problem. I removed the satellite from HA and changed its name.  Reset the service on the satellite and HA rediscovered and is working.

**Comment by pcwii** [comment]
Thanks @zac9

> @pcwii I also just had this problem. I removed the satellite from HA and changed its name. Reset the service on the satellite and HA rediscovered and is working.

Thanks, will give that a try.

**Comment by FutureProofHomes** [comment]
@pcwii How'd things go.  Can we close this ticket?

**Comment by pcwii** [comment]
I was actually trying the recommendation when you sent this message. It looks like the recommendation works. 
1. Copied my systemd service to the new enhanced service name.
2. Renamed the existing `-name` in the original systemd service.
3. Deleted the original device from the Wyoming integration in HA.
4. Rebooted the satellite.
5. Added the newly named device to the Wyoming integration in HA.
6. Confirmed it was working. 
7. Disabled the satellite and open wake word services.
8. Updated the "enhanced" service. 
9. Enabled the new "enhanced" service. 
10. Rebooted the satellite. 
11. Added the enhanced satellite with the original name to the Wyoming integration in HA, and it was found successfully. 
12. Removed the temporarily named original Wyoming integration in HA.
All 👍 
You can close this ticket.  Thanks!

**Comment by FutureProofHomes** [comment]
Closing!  Thanks for the details!
