### ISSUE TITLE
Something went wrong: failed to load functions. Verify functions are valid in a yaml format

### ISSUE THREAD

**Issue by absarbandayy** [FutureProofHomes/wyoming-enhancements#17]
at the last step of adding specs into the llm i am getting this issue Something went wrong: failed to load functions. Verify functions are valid in a yaml format.

**Comment by avigeilpro** [comment]
You should copy/paste the full area of "fonctions" here that we could see what is wrong.

**Comment by absarbandayy** [comment]
resolved was issue with in copying
