### ISSUE TITLE
PulseAudio issue on Raspbery Pi 4

### ISSUE THREAD

**Issue by n8ohu** [FutureProofHomes/wyoming-enhancements#26]
I've been trying to configure this on a Raspberry Pi 4 with 4GB of RAM, but have been unable to proceed past the configuration of PulseAudio. It seems to work, but when I try to play the audio file like I have done on two Raspberry Pi Zero 2 W boards, there is no audio output. I'm puzzled by this, because I'm following the guide exactly as written. Has anyone been able to successfully implement this on the full size Pi 4?

**Comment by AnEnglishSkull** [comment]
try pluging into the pi's port rather than the mic boards headphone jack, Im currently having an issue trying to get pulse to output over the soundboard

**Comment by n8ohu** [comment]
I'm going to close this, as a solution has been found for it.
