### ISSUE TITLE
pulse outputing via built in headphone jack rather than seed-2mic

### ISSUE THREAD

**Issue by AnEnglishSkull** [FutureProofHomes/wyoming-enhancements#27]
pulse audio not outputting over the seeed-2mic but only outputing via the headphone jack of my pi 3 model b, worked via the seed boad before installing the pulse steps for ducking

**Comment by AnEnglishSkull** [comment]
good luck please post if it worked or not

**Comment by AnEnglishSkull** [comment]
I figured it out. You can change the default output device with 
"pactl set-default-sink" first run "pactl list short sinks" to list you available output devices 
"0       alsa_output.platform-bcm2835_audio.analog-stereo        module-alsa-card.c      s16le 2ch 44100Hz       RUNNING                                                                                                                                       1       alsa_output.platform-soc_sound.stereo-fallback  module-alsa-card.c      s16le 2ch 44100Hz       SUSPENDED" if something is currently playing it will say  "running" and you other device will say idle or suspended in my case running "pactl set-default-sink alsa_output.platform-soc_sound.stereo-fallback" set it to output with the seeed board rather than the pi's onboard jack

**Comment by AnEnglishSkull** [comment]
hope this helps anybody else like me who is knew to pulse in general

**Comment by n8ohu** [comment]
Thanks for figuring it out. What I tried didn't work.

**Comment by ra31el71** [comment]
Hi!
Mine says:
0       alsa_output.platform-3f902000.hdmi.hdmi-stereo  module-alsa-card.c      s16le 2ch 44100Hz       SUSPENDED
1       alsa_output.platform-soc_sound.stereo-fallback  module-alsa-card.c      s16le 2ch 44100Hz       SUSPENDED
How can I enable one of those?
