### ISSUE TITLE
is the combo of Wyoming satellite end snapcast client really usable on pi 2w?

### ISSUE THREAD

**Issue by eleaner** [FutureProofHomes/wyoming-enhancements#44]
Thanks for the tutorial, it works
but it feels like both functionalities are too much for one pi 2w.

streamed audio will randomly break for a few seconds, voice recognition will work multiple times and then suddenly hand (with yellow light on).
The problems seem to be less prominent when one (or the other) is switch off.

did anyone experience such problems too?

**Comment by debdalerichard** [comment]
I have this setup and it works flawlessly? have you got a busy wifi local network? i found creating another network for IOT devices and snapcast etc... made it function more smoothly as your normal WIFI might be to busy???

**Comment by eleaner** [comment]
bingo! wifi was the problem
for starters my wifi at home is not great
in addition I used USB powered speaker, it looks like it generated heaps of interference.

thank you!
