### ISSUE TITLE
Snapcast client fails to start

### ISSUE THREAD

**Issue by SpencerDub** [FutureProofHomes/wyoming-enhancements#49]
I have followed the directions in [the Snapcast tutorial](https://github.com/FutureProofHomes/wyoming-enhancements/blob/master/snapcast/docs/3_install_snapclient.md), but at Step 9, `snapclient.service` fails to start.

## System
* Device: Raspberry Pi Zero 2 W and [Waveshare ReSpeaker HAT](https://www.amazon.com/dp/B098R7TTM4?ref=ppx_yo2ov_dt_b_fed_asin_title)
* OS: Raspberry Pi OS (64-bit) Lite, as specified in the [Wyoming Satellite tutorial](https://github.com/rhasspy/wyoming-satellite/blob/master/docs/tutorial_2mic.md) (`hostnamectl` reports "Debian GNU/Linux 12 (bookworm)")
* Previous setup: Followed the [Wyoming Satellite tutorial](https://github.com/rhasspy/wyoming-satellite/blob/master/docs/tutorial_2mic.md), followed steps [1](https://github.com/FutureProofHomes/wyoming-enhancements/blob/master/snapcast/docs/1_install_snapserver_addons.md) and [2](https://github.com/FutureProofHomes/wyoming-enhancements/blob/master/snapcast/docs/2_install_pulseaudio.md) in the FutureProofHomes tutorial.

## Exceptions
The only exception to the tutorial flow is that at Step 3.4, installing SnapClient, I used the URL of the most recent version instead:

```
wget https://github.com/badaix/snapcast/releases/download/v0.29.0/snapclient_0.29.0-1_armhf_bookworm.deb
sudo apt install ./snapclient_0.29.0-1_armhf_bookworm.deb 
```

## Steps to Reproduce
1. Restart the Pi, or run `sudo systemctl start snapclient.service`.
2. Run `sudo systemctl status pulseaudio.service snapclient.service` to check the status of those services.

## Expected Outcome
`systemctl` reports that both `pulseaudio.service` and `snapclient.service` are running, with green circles beside them.

## Encountered Outcome
`pulseaudio.service` is reported to be running; `snapclient.service` is not.

```
● pulseaudio.service - PulseAudio system server
     Loaded: loaded (/etc/systemd/system/pulseaudio.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-09-05 10:04:23 PDT; 46min ago
   Main PID: 410 (pulseaudio)
      Tasks: 3 (limit: 174)
        CPU: 748ms
     CGroup: /system.slice/pulseaudio.service
             └─410 pulseaudio --daemonize=no --system --realtime --log-target=journal

Sep 05 10:04:19 comet pulseaudio[410]: Home directory of user 'pulse' is not '/var/run/pulse', ignoring.
Sep 05 10:04:19 comet pulseaudio[410]: OK, so you are running PA in system mode. Please make sure that you actually do wa>
Sep 05 10:04:19 comet pulseaudio[410]: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User>
Sep 05 10:04:22 comet pulseaudio[410]: Failed to find a working profile.
Sep 05 10:04:22 comet pulseaudio[410]: Failed to load module "module-alsa-card" (argument: "device_id="0" name="platform->
Sep 05 10:04:23 comet pulseaudio[410]: Failed to open cookie file '/var/run/pulse/.config/pulse/cookie': No such file or >
Sep 05 10:04:23 comet pulseaudio[410]: Failed to load authentication key '/var/run/pulse/.config/pulse/cookie': No such f>
Sep 05 10:04:23 comet pulseaudio[410]: Failed to open cookie file '/var/run/pulse/.pulse-cookie': No such file or directo>
Sep 05 10:04:23 comet pulseaudio[410]: Failed to load authentication key '/var/run/pulse/.pulse-cookie': No such file or >
Sep 05 10:04:23 comet systemd[1]: Started pulseaudio.service - PulseAudio system server.

× snapclient.service - Snapcast client
     Loaded: loaded (/etc/systemd/system/snapclient.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-09-05 10:50:01 PDT; 58s ago
   Duration: 121ms
       Docs: man:snapclient(1)
    Process: 983 ExecStart=/usr/bin/snapclient --logsink=system $SNAPCLIENT_OPTS (code=exited, status=1/FAILURE)
   Main PID: 983 (code=exited, status=1/FAILURE)
        CPU: 90ms

Sep 05 10:50:01 comet systemd[1]: snapclient.service: Scheduled restart job, restart counter is at 5.
Sep 05 10:50:01 comet systemd[1]: Stopped snapclient.service - Snapcast client.
Sep 05 10:50:01 comet systemd[1]: snapclient.service: Start request repeated too quickly.
Sep 05 10:50:01 comet systemd[1]: snapclient.service: Failed with result 'exit-code'.
Sep 05 10:50:01 comet systemd[1]: Failed to start snapclient.service - Snapcast client.
```

## Logs and Other Info
I ran `journalctl -u snapclient --follow > snapclient.log` and restarted the service. Here is one section of the log, which appears to repeat:

```
Sep 05 11:00:34 comet systemd[1]: Started snapclient.service - Snapcast client.
Sep 05 11:00:34 comet snapclient[1116]: PCM device "default" not found
Sep 05 11:00:34 comet snapclient[1116]: Version 0.29.0, revision 208066e5
Sep 05 11:00:34 comet snapclient[1116]: Resolving host IP for: [HA internal IP]
Sep 05 11:00:34 comet snapclient[1116]: Connecting to [HA internal IP:Snapcast port]
Sep 05 11:00:34 comet snapclient[1116]: Connected to [HA internal IP]
Sep 05 11:00:34 comet snapclient[1116]: My MAC: "[redacted]", socket: 9
Sep 05 11:00:34 comet snapclient[1116]: ServerSettings - buffer: 333, latency: 0, volume: 100, muted: 0
Sep 05 11:00:34 comet snapclient[1116]: Codec: flac, sampleformat: 44100:16:2
Sep 05 11:00:34 comet snapclient[1116]: Exception: No audio player support for: pulse
Sep 05 11:00:34 comet snapclient[1116]: Snapclient terminated.
Sep 05 11:00:34 comet systemd[1]: snapclient.service: Main process exited, code=exited, status=1/FAILURE
Sep 05 11:00:34 comet systemd[1]: snapclient.service: Failed with result 'exit-code'.
Sep 05 11:00:34 comet systemd[1]: snapclient.service: Scheduled restart job, restart counter is at 3.
Sep 05 11:00:34 comet systemd[1]: Stopped snapclient.service - Snapcast client.
```

If I'm reading correctly, Snapclient is failing because there is "no audio player support for pulse".

Just to confirm, here is the `SNAPCLIENT_OPTS` line from `/etc/default/snapclient`:

```
SNAPCLIENT_OPTS="-h [HA internal IP] --player pulse:property=media.role=music --sampleformat 44100:16:*"
```

What do I need to do to solve the "No audio player support for pulse" issue that Snapclient is presenting me?

## Other Research
[This comment](https://github.com/badaix/snapcast/issues/1183#issuecomment-2187228312) on the Snapcast repo suggests that Snapclient needs to be run "as a user unit". However, I don't know what parts of the existing setup I would undo, or how, before following the steps that user offers—or if that is even a relevant solution.

**Comment by SpencerDub** [comment]
Ah, reading helps. The [snapclient v0.29.0 release](https://github.com/badaix/snapcast/releases/tag/v0.29.0) I linked included this line:

> The packages snapclient_<version>_<arch>_<debian>_with-pulse.deb are built with pulse audio player backend support (i.e. do support --player pulse) and thus require the PulseAudio dependencies.

Removing the old version of snapclient (`sudo apt-get remove snapclient:armhf`) and re-downloading the `_with-pulse.deb` version and installing it fixed this issue.

**Comment by Blink515** [comment]
This shouldn't be closed so the documentation will actually be updated. Hopefully
